services:
  memgraph:
    image: memgraph/memgraph-mage:3.1.0-memgraph-3.1.0
    ports:
      - 7687:7687
      - 7444:7444
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    command: ["--log-level=INFO"]

  lab:
    image: memgraph/lab:3.1.0
    ports:
      - 3000:3000
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

volumes:
  mg_lib:
  mg_log:
  mg_etc:
