name: Release Memgraph docker extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 2.20.0). Should match Memgraph's version."
        required: true
        type: string

jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          tags: memgraph/memgraph-docker-extension:${{ inputs.version }}
          push: true
